/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.vorobey;

import by.vorobey.shoppingBasket.dao.DAOTable;
import by.vorobey.shoppingBasket.model.Basket;
import by.vorobey.shoppingBasket.model.Product;
import by.vorobey.shoppingBasket.server.Order;
import by.vorobey.shoppingBasket.utils.DBUtils;
import by.vorobey.shoppingBasket.view.Print;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import java.util.*;

public class App {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(DBUtils.class);

        DAOTable daoTable = context.getBean(DAOTable.class);
        Print print = context.getBean(Print.class);
        Order order = context.getBean(Order.class);

        //daoTable.createTable();
        //daoTable.insertTable();

        ArrayList<Product> list = (ArrayList<Product>) daoTable.findAll();
        print.printWarehouse(list);

        Basket basket = order.addProduct(daoTable);
        /*System.out.println("------------------------");
        System.out.println(basket);
        System.out.println("------------------------");*/

        print.printCheck(basket);



    }
}
