spring:
  sql.init.mode: always
  main:
    banner-mode: "off"
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://localhost:5432/clevertec?useSSL=false&amp;serverTimezone=UTC}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  application:
    admin:
      enabled: true

#server:
#  servlet:
#    context-path: /springboot
